name: Auto PR Summary

on:
  pull_request:
    types: [opened, edited]

jobs:
  generate_summary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate PR Summary
      run: |
        FILE_COUNT=$(git diff --name-only HEAD~1 | wc -l)
        LANGUAGES=$(github-linguist)
        echo "## PR Summary
        - Files Changed: $FILE_COUNT
        - Languages Used: $LANGUAGES
        - Estimated Review Time: $((FILE_COUNT * 2)) minutes" > summary.md

    - name: Post comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          $(cat summary.md)
